CREATE DATABASE IF NOT EXISTS nutricare;
USE nutricare;

CREATE TABLE IF NOT EXISTS Nutricionista(
    id INT AUTO_INCREMENT PRIMARY KEY,
    cfn VARCHAR(3) NOT NULL UNIQUE,
    nome VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Paciente(
    id INT AUTO_INCREMENT PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE, 
    nome VARCHAR(255) NOT NULL,
    genero CHAR NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE, 
    senha VARCHAR(255) NOT NULL, 
    ficha INT
);

