services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_storage:/var/lib/mysql/
    networks:
      - nutricare_mysql
    ports:
      - 3307:3306
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - nutricare_mysql
    
volumes:
  mysql_storage:

networks:
  nutricare_mysql:
    driver: bridge